### ISSUE TITLE
Welcome the organizer of a GDG with a special message

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#111]
When the user is one of the organizers of the user's home GDG set a flag and a message to congratulate for the great work.

In the future, the gdg manager will have an extra menu for additional actions.

**Comment by tasomaniac** [comment]
I am starting to work on this. I will show a simple dialog. 
Anybody have something cool in mind? Like a badge, logo to include in the welcome dialog? Or a welcome gif?

**Comment by HenriqueRocha** [comment]
Maybe an overlay with some nice image with a button saying "You're awesome!" :D

**Comment by tasomaniac** [comment]
@friedger I saw your congrats branch doing some work on this. I suppose it just shows a Toast message. Should I continue on that?

**Comment by friedger** [comment]
In https://github.com/gdg-x/frisbee/tree/feature/add_leads_fragment a 4th tab is added to the home chapter screen

**Comment by friedger** [comment]
fixed by #331

**Comment by tasomaniac** [comment]
I am re-openning it because there are these problems in the current implementation:

- It doesn't show "FOR LEADS" section unless you open the Arrow section. Arrow page first check that if the user is organizer.
- For Leads section persists on app logout. This is actually a bug out of this issue's scope but we should fix that. We should delete all user related info on app logout. 
- We should have event listener on the Home GDG page to listen the login/logout changes. For Leads section should be added dynamically after login.

**Comment by tasomaniac** [comment]
I will re-open this issue because I had problems with it. 
Login is not working in debug builds. We should fix it asap. 
Login worked for me for a local release build but I had a problem with Organizer Checking. It doesn't enable Lead page for me. 
Organizer Checker work fine on production on Arrow page.
