### ISSUE TITLE
Redo icons for material nav drawer

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#233]
Redo icons for nav drawer

**Comment by HenriqueRocha** [comment]
What do you guys think about these icons? @friedger @tasomaniac @stefanhoth 
![device-2015-02-28-123437](https://cloud.githubusercontent.com/assets/140122/6426044/6526df9e-bf46-11e4-918f-26ed4096649f.png)

If you like them I'll create PR with them.

**Comment by stefanhoth** [comment]
These look cool. :+1: where are they from?

**Comment by HenriqueRocha** [comment]
The WTM I had to do it myself in GIMP, but the others are from the released
material icons by Google.
On 28 Feb 2015 14:32, "Stefan Hoth" <notifications@github.com> wrote:

> These look cool. [image: :+1:] where are they from?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdg-x/frisbee/issues/233#issuecomment-76526203>.
>

-- 
Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93

**Comment by friedger** [comment]
The Arrow icon could be more gamish maybe use av/Games from https://google.github.io/material-design-icons/

The academic hat (school) might fit better for the study jam.

Then for experts the mentoring icon (as used on https://developers.google.com/experts/about) could be used

**Comment by friedger** [comment]
Do you have an icon for Google I/O extended?

**Comment by HenriqueRocha** [comment]
No, I also have to create that one myself. I'll do it when I arrive home
and apply your suggestions also. :+1:
On 28 Feb 2015 15:24, "Friedger Müffke" <notifications@github.com> wrote:

> Do you have an icon for Google I/O extended?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gdg-x/frisbee/issues/233#issuecomment-76527950>.
>

-- 
Disclaimer: The information in this e-mail and any attachments is the 
property of Novoda Ltd and is confidential and may be legally privileged. 
This e-mail is intended solely for the person or organisation to which it 
is addressed. Any disclosure, copying or other use of the information by 
any person or organisation who is not the intended recipient is strictly 
prohibited and may be unlawful. If you have received this e-mail in error, 
please inform the sender immediately and delete/destroy this e-mail and any 
copies of it. Novoda Ltd has taken reasonable precautions to minimise the 
risk of any software viruses which may damage your systems, but we advise 
that you take the necessary steps to ensure that no virus contamination is 
suffered. Novoda Ltd does not accept any liability for any loss or damage 
caused by the transmission of any virus.

Novoda Ltd, Company No: 347444, Registered in Scotland Registered 
Office: C/O Alexander Sloan, 38 Cadogan Street, Glasgow, G2 7HF, Scotland.  VAT 
Registration Number  GB 984 2525 93

**Comment by mauimauer** [comment]
Awesome choice. Don't want to be picky here but the WTM icon seems to have some rough edges (on the bottom part of the W. I wonder if that happened when you scaled down the icon.

**Comment by HenriqueRocha** [comment]
@mauimauer I don't now what happened. Do you have a big version of the icon? Maybe I didn't activate the anti-aliasing option when I painted the icon grey. My design skills with GIMP are ultra basic. :(
