### ISSUE TITLE
Remove build timestamp from BuildConfig

### ISSUE THREAD

**Issue by friedger** [gdg-x/frisbee#553]
Use paperwork instead of BuildConfig for gitSha and timestamp

Paperwork is available at
https://github.com/zsoltk/paperwork

**Comment by tasomaniac** [comment]
I've asked about this in a Slack group. I think we should fix that but I am against adding additional plugin. 

Instead of `new Date()` using gitTimestamp improves it a lot

`def gitTimestamp = 'git log -n 1 --format=%at'.execute([], rootDir).text.trim()`

It will do dexing when git timestamp changes which happens when we commit. It think it is ok to do that. Dexing is done every time we change java code anyways.
